---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-machine-api

resources:
  - job.yaml
  - rbac.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-aws-cpu-infra-machineset
    namespace: openshift-machine-api
    files:
      - job.sh
      - machineset-patch.yaml
