apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    cluster.ocs.openshift.io/openshift-storage: ""
    machine.openshift.io/cluster-api-machine-role: infra
    machine.openshift.io/cluster-api-machine-type: infra
spec:
  replicas: 3
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        node-role.kubernetes.io/infra: ""
        cluster.ocs.openshift.io/openshift-storage: ""
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          cluster.ocs.openshift.io/openshift-storage: ""
